# Generated by Django 5.1.3 on 2024-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('number_first', models.CharField(default='', max_length=3)),
                ('number_second', models.CharField(default='', max_length=4)),
                ('number_third', models.CharField(default='', max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('reser_code', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_time', models.DateTimeField()),
                ('isvalid', models.BooleanField(default='TRUE')),
                ('possible_team', models.IntegerField(default=4)),
            ],
        ),
    ]
