# Generated by Django 5.1.3 on 2024-11-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(default='', max_length=50)),
                ('reservation_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='null.reservation')),
            ],
        ),
    ]
