# Generated by Django 5.1.3 on 2024-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_first',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_second',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_third',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
