# Generated by Django 5.1.3 on 2024-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('null', '0005_reservation_age_reservation_email_reservation_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_first',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_second',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_third',
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
